"""Final report data assembled before Jinja2 rendering."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, HttpUrl
from typing import Literal

from jobhunter.models.facts import (
    AggregatedFindings,
    BusinessFacts,
    CompanyProfile,
    JudicialFacts,
    NewsFacts,
    ReviewFacts,
)
from jobhunter.models.query import CompanyQuery
from jobhunter.models.scoring import AxisScore

Confidence = Literal["high", "medium", "low"]


class SourceEntry(BaseModel):
    domain: str
    title: str
    url: HttpUrl


class PeerCompany(BaseModel):
    """v0.1.15 — Compact summary of a same-industry peer company.

    Built by `pipeline._build_peer_summary()` from a lightweight (no-LLM-
    consolidation) re-run of the main pipeline. Stored in `ReportData.
    peer_comparison` (as dict) and rendered as a comparison table next to
    the target company.
    """
    name: str
    industry: str | None = None
    overall_score: float | None = None
    axis_overtime: int | None = None
    axis_judicial: int | None = None
    axis_salary: int | None = None
    axis_business: int | None = None
    axis_vibe: int | None = None
    salary_median_k: float | None = None
    overtime_pattern: str | None = None
    case_count_total: int | None = None
    news_sentiment: Literal["positive", "neutral", "negative", "mixed"] | None = None
    error: str | None = None  # non-null if peer run failed


class ReportData(BaseModel):
    query: CompanyQuery
    generated_at: datetime
    findings: AggregatedFindings | None = None
    axes: list[AxisScore] = Field(default_factory=list)
    business_facts: BusinessFacts | None = None
    review_facts: ReviewFacts | None = None
    news_facts: NewsFacts | None = None
    judicial_facts: JudicialFacts | None = None
    company_profile: CompanyProfile | None = None
    interview_questions: list[str] = Field(default_factory=list)
    sources: list[SourceEntry] = Field(default_factory=list)
    overall_confidence: Confidence = "low"
    # Per-chapter confidence (company / business / judicial / reviews / news + overall)
    # Drives the small 「数据充足 / 部分缺失 / 需人工核查」badge next to each
    # chapter title. Computed from whether raw items landed AND extract pulled
    # structured signal out of them.
    chapter_confidence: dict[str, Confidence] = Field(default_factory=dict)
    data_gaps: list[str] = Field(default_factory=list)

    # v0.1.13 — Editorial voice + data stories
    # edit_notes: per-chapter editor's-note aside ("编辑手记"), generated by the
    #   builder from facts + industry baseline. Shown next to chapter-takeaway.
    # data_stories: per-chapter "过去 12 个月里..." lines that contextualize
    #   raw numbers against industry averages (e.g. "比同行平均高 23%").
    # Industry key used to compute data stories (defaults to "default" baseline
    # when unknown).
    edit_notes: dict[str, str] = Field(default_factory=dict)
    data_stories: dict[str, list[str]] = Field(default_factory=dict)
    industry_key: str = "default"

    # v0.1.15 — 1mo / 3mo / 6mo 试用期观察清单 + 同行业对比
    trial_checklist: dict[str, list[str]] = Field(default_factory=dict)
    peer_comparison: list[dict] = Field(default_factory=list)  # PeerCompany.model_dump() list
